apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-hybr
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine:latest
        command: ["echo"]
        args: ["Hello World Hybr"]